import { BibleBookMap, BibleBookKey } from '../../models/bible';


export const bibleBooks: BibleBookMap = {
    [BibleBookKey.Gen]: { key: BibleBookKey.Gen, full: 'Genesis', abbr: 'Gen.' },
    [BibleBookKey.Ex]: { key: BibleBookKey.Ex, full: 'Exodus', abbr: 'Ex.' },
    [BibleBookKey.Lev]: { key: BibleBookKey.Lev, full: 'Leviticus', abbr: 'Lev.' },
    [BibleBookKey.Num]: { key: BibleBookKey.Num, full: 'Numbers', abbr: 'Num.' },
    [BibleBookKey.Deut]: { key: BibleBookKey.Deut, full: 'Deuteronomy', abbr: 'Deut.' },
    [BibleBookKey.Josh]: { key: BibleBookKey.Josh, full: 'Joshua', abbr: 'Josh.' },
    [BibleBookKey.Judg]: { key: BibleBookKey.Judg, full: 'Judges', abbr: 'Judg.' },
    [BibleBookKey.Ruth]: { key: BibleBookKey.Ruth, full: 'Ruth', abbr: 'Ruth' },
    [BibleBookKey.Sam1]: { key: BibleBookKey.Sam1, full: '1 Samuel', abbr: '1 Sam.' },
    [BibleBookKey.Sam2]: { key: BibleBookKey.Sam2, full: '2 Samuel', abbr: '2 Sam.' },
    [BibleBookKey.Kings1]: { key: BibleBookKey.Kings1, full: '1 Kings', abbr: '1 Kings' },
    [BibleBookKey.Kings2]: { key: BibleBookKey.Kings2, full: '2 Kings', abbr: '2 Kings' },
    [BibleBookKey.Chron1]: { key: BibleBookKey.Chron1, full: '1 Chronicles', abbr: '1 Chron.' },
    [BibleBookKey.Chron2]: { key: BibleBookKey.Chron2, full: '2 Chronicles', abbr: '2 Chron.' },
    [BibleBookKey.Ezra]: { key: BibleBookKey.Ezra, full: 'Ezra', abbr: 'Ezra' },
    [BibleBookKey.Neh]: { key: BibleBookKey.Neh, full: 'Nehemiah', abbr: 'Neh.' },
    [BibleBookKey.Est]: { key: BibleBookKey.Est, full: 'Esther', abbr: 'Est.' },
    [BibleBookKey.Job]: { key: BibleBookKey.Job, full: 'Job', abbr: 'Job' },
    [BibleBookKey.Ps]: { key: BibleBookKey.Ps, full: 'Psalms', abbr: 'Ps.' },
    [BibleBookKey.Prov]: { key: BibleBookKey.Prov, full: 'Proverbs', abbr: 'Prov.' },
    [BibleBookKey.Eccles]: { key: BibleBookKey.Eccles, full: 'Ecclesiastes', abbr: 'Eccles.' },
    [BibleBookKey.Song]: { key: BibleBookKey.Song, full: 'Song of Solomon', abbr: 'Song' },
    [BibleBookKey.Isa]: { key: BibleBookKey.Isa, full: 'Isaiah', abbr: 'Isa.' },
    [BibleBookKey.Jer]: { key: BibleBookKey.Jer, full: 'Jeremiah', abbr: 'Jer.' },
    [BibleBookKey.Lam]: { key: BibleBookKey.Lam, full: 'Lamentations', abbr: 'Lam.' },
    [BibleBookKey.Ezek]: { key: BibleBookKey.Ezek, full: 'Ezekiel', abbr: 'Ezek.' },
    [BibleBookKey.Dan]: { key: BibleBookKey.Dan, full: 'Daniel', abbr: 'Dan.' },
    [BibleBookKey.Hos]: { key: BibleBookKey.Hos, full: 'Hosea', abbr: 'Hos.' },
    [BibleBookKey.Joel]: { key: BibleBookKey.Joel, full: 'Joel', abbr: 'Joel' },
    [BibleBookKey.Amos]: { key: BibleBookKey.Amos, full: 'Amos', abbr: 'Amos' },
    [BibleBookKey.Obad]: { key: BibleBookKey.Obad, full: 'Obadiah', abbr: 'Obad.' },
    [BibleBookKey.Jonah]: { key: BibleBookKey.Jonah, full: 'Jonah', abbr: 'Jonah' },
    [BibleBookKey.Mic]: { key: BibleBookKey.Mic, full: 'Micah', abbr: 'Mic.' },
    [BibleBookKey.Nah]: { key: BibleBookKey.Nah, full: 'Nahum', abbr: 'Nah.' },
    [BibleBookKey.Hab]: { key: BibleBookKey.Hab, full: 'Habakkuk', abbr: 'Hab.' },
    [BibleBookKey.Zeph]: { key: BibleBookKey.Zeph, full: 'Zephaniah', abbr: 'Zeph.' },
    [BibleBookKey.Hag]: { key: BibleBookKey.Hag, full: 'Haggai', abbr: 'Hag.' },
    [BibleBookKey.Zech]: { key: BibleBookKey.Zech, full: 'Zechariah', abbr: 'Zech.' },
    [BibleBookKey.Mal]: { key: BibleBookKey.Mal, full: 'Malachi', abbr: 'Mal.' },
    [BibleBookKey.Matt]: { key: BibleBookKey.Matt, full: 'Matthew', abbr: 'Matt.' },
    [BibleBookKey.Mark]: { key: BibleBookKey.Mark, full: 'Mark', abbr: 'Mark' },
    [BibleBookKey.Luke]: { key: BibleBookKey.Luke, full: 'Luke', abbr: 'Luke' },
    [BibleBookKey.John]: { key: BibleBookKey.John, full: 'John', abbr: 'John' },
    [BibleBookKey.Acts]: { key: BibleBookKey.Acts, full: 'Acts', abbr: 'Acts' },
    [BibleBookKey.Rom]: { key: BibleBookKey.Rom, full: 'Romans', abbr: 'Rom.' },
    [BibleBookKey.Cor1]: { key: BibleBookKey.Cor1, full: '1 Corinthians', abbr: '1 Cor.' },
    [BibleBookKey.Cor2]: { key: BibleBookKey.Cor2, full: '2 Corinthians', abbr: '2 Cor.' },
    [BibleBookKey.Gal]: { key: BibleBookKey.Gal, full: 'Galatians', abbr: 'Gal.' },
    [BibleBookKey.Eph]: { key: BibleBookKey.Eph, full: 'Ephesians', abbr: 'Eph.' },
    [BibleBookKey.Phil]: { key: BibleBookKey.Phil, full: 'Philippians', abbr: 'Phil.' },
    [BibleBookKey.Col]: { key: BibleBookKey.Col, full: 'Colossians', abbr: 'Col.' },
    [BibleBookKey.Thess1]: { key: BibleBookKey.Thess1, full: '1 Thessalonians', abbr: '1 Thess.' },
    [BibleBookKey.Thess2]: { key: BibleBookKey.Thess2, full: '2 Thessalonians', abbr: '2 Thess.' },
    [BibleBookKey.Tim1]: { key: BibleBookKey.Tim1, full: '1 Timothy', abbr: '1 Tim.' },
    [BibleBookKey.Tim2]: { key: BibleBookKey.Tim2, full: '2 Timothy', abbr: '2 Tim.' },
    [BibleBookKey.Titus]: { key: BibleBookKey.Titus, full: 'Titus', abbr: 'Titus' },
    [BibleBookKey.Philem]: { key: BibleBookKey.Philem, full: 'Philemon', abbr: 'Philem.' },
    [BibleBookKey.Heb]: { key: BibleBookKey.Heb, full: 'Hebrews', abbr: 'Heb.' },
    [BibleBookKey.James]: { key: BibleBookKey.James, full: 'James', abbr: 'James' },
    [BibleBookKey.Pet1]: { key: BibleBookKey.Pet1, full: '1 Peter', abbr: '1 Pet.' },
    [BibleBookKey.Pet2]: { key: BibleBookKey.Pet2, full: '2 Peter', abbr: '2 Pet.' },
    [BibleBookKey.John1]: { key: BibleBookKey.John1, full: '1 John', abbr: '1 John' },
    [BibleBookKey.John2]: { key: BibleBookKey.John2, full: '2 John', abbr: '2 John' },
    [BibleBookKey.John3]: { key: BibleBookKey.John3, full: '3 John', abbr: '3 John' },
    [BibleBookKey.Jude]: { key: BibleBookKey.Jude, full: 'Jude', abbr: 'Jude' },
    [BibleBookKey.Rev]: { key: BibleBookKey.Rev, full: 'Revelation', abbr: 'Rev.' },
};
