import { VerseTagMap, VerseTagKey } from '../../models/tags';

// tslint:disable:max-line-length
export const tags: VerseTagMap = {
    [VerseTagKey.Authority]: { key: VerseTagKey.Authority, name: 'Authority', description: 'Jesus demonstrated great authority over disease, nature, demons, etc. Most noteworthy is perhaps how Jesus performs the miracles without explicitly calling on the help of or doing them in the name of God.' },
    [VerseTagKey.Blasphemy]: { key: VerseTagKey.Blasphemy, name: 'Blasphemy', description: 'Jesus is sometimes accused of blasphemy, usually when He makes much of Himself.' },
    [VerseTagKey.Bridegroom]: { key: VerseTagKey.Bridegroom, name: 'Bridegroom', description: 'Jesus claims to be the bridegroom of the church, His bride.' },
    [VerseTagKey.Christ]: { key: VerseTagKey.Christ, name: 'Christ', description: 'Jeus is the Christ (or promised Messiah), often identified as the son of David.' },
    [VerseTagKey.Clean]: { key: VerseTagKey.Clean, name: 'Clean', description: 'Religious cleanliness is tightly tied to an understanding of sinfulness. So healing an unclean person suggests an authority over sin.' },
    [VerseTagKey.Clouds]: { key: VerseTagKey.Clouds, name: 'Clouds', description: 'Clouds are used in the Bible to represent the presence and glory of God (eg. Ex. 16:10, Ex. 40:34-35, Num. 11:25) ' },
    [VerseTagKey.Creator]: { key: VerseTagKey.Creator, name: 'Creator', description: 'All things were created through Jesus.' },
    [VerseTagKey.Demons]: { key: VerseTagKey.Demons, name: 'Demons', description: 'Words spoken by demons' },
    [VerseTagKey.Eternal]: { key: VerseTagKey.Eternal, name: 'Eternal', description: 'Jesus is the same yesterday and today and forever. In the beginning He already was and He always will be.' },
    [VerseTagKey.Faith]: { key: VerseTagKey.Faith, name: 'Faith', description: 'Jesus is the object of people\'s faith.' },
    [VerseTagKey.FP]: { key: VerseTagKey.FP, name: 'Fulfilled Prophecy', description: 'Jesus is the fulfillment of many prophecies from the Old Testament' },
    [VerseTagKey.Glory]: { key: VerseTagKey.Glory, name: 'Glory', description: 'Great glory is ascribed to Jesus; even the glory of the Father.' },
    [VerseTagKey.God]: { key: VerseTagKey.God, name: 'God', description: 'Jesus is sometimes explicitly and sometimes implicitly made out to be God' },
    [VerseTagKey.Greater]: { key: VerseTagKey.Greater, name: 'Greater', description: 'Jesus is greater than a great many great people and things' },
    [VerseTagKey.Heaven]: { key: VerseTagKey.Heaven, name: 'Heaven', description: 'Jesus came down from Heaven, indicating that he existed before he was born' },
    [VerseTagKey.Himself]: { key: VerseTagKey.Himself, name: 'Himself', description: 'Particularly significant statements Jesus made about Himself' },
    [VerseTagKey.His]: { key: VerseTagKey.His, name: 'His', description: 'People, beings, things and positions are described as belonging to Jesus' },
    [VerseTagKey.Holy]: { key: VerseTagKey.Holy, name: 'Holy', description: 'Jesus is holy and pure.' },
    [VerseTagKey.Honour]: { key: VerseTagKey.Honour, name: 'Honour', description: 'Jesus being honoured is an extroardinary/special way' },
    [VerseTagKey.Humility]: { key: VerseTagKey.Humility, name: 'Humility', description: 'Verses that help explain Jesus\' "lowliness". I.e. why He sometimes distances Himself from equality with God' },
    [VerseTagKey.I_AM]: { key: VerseTagKey.I_AM, name: 'I AM', description: 'The God of the Old Testament reveals Himself to Moses as the "I AM" (Ex. 3:14). Jesus seems to use this same title.' },
    [VerseTagKey.Judge]: { key: VerseTagKey.Judge, name: 'Judge', description: 'Jesus will judge the world one day' },
    [VerseTagKey.King]: { key: VerseTagKey.King, name: 'King', description: 'Jesus is the king of an eternal kingdom.' },
    [VerseTagKey.Life]: { key: VerseTagKey.Life, name: 'Life', description: 'Jesus is not only the source of life, but life itself.' },
    [VerseTagKey.Lord]: { key: VerseTagKey.Lord, name: 'Lord', description: 'Jesus is a lord. In fact many passages refer to both God and Jesus as lord using the same Greek word (Kyrios) without attempting to make any distinction' },
    [VerseTagKey.Lowly]: { key: VerseTagKey.Lowly, name: 'Lowly', description: 'Jesus sometimes distanced Himself from Deity.' },
    [VerseTagKey.Name]: { key: VerseTagKey.Name, name: 'Name', description: 'Jesus\' "name" being used, emphasized or honoured' },
    [VerseTagKey.Omnipresent]: { key: VerseTagKey.Omnipresent, name: 'Omnipresent', description: 'Jesus makes claims that require Him to be in multiple places at the same time. ' },
    [VerseTagKey.Omniscient]: { key: VerseTagKey.Omniscient, name: 'Omniscient', description: 'Jesus\' knowledge is hard to overexaggerate.' },
    [VerseTagKey.One]: { key: VerseTagKey.One, name: 'One', description: 'Jesus, the true Son, is intimately united with His Father.' },
    [VerseTagKey.Power]: { key: VerseTagKey.Power, name: 'Power', description: 'Jesus demonstrated power over disease, demons and nature.' },
    [VerseTagKey.Right_Hand]: { key: VerseTagKey.Right_Hand, name: 'Right Hand', description: 'Jesus sits at the right hand of God.' },
    [VerseTagKey.Saviour]: { key: VerseTagKey.Saviour, name: 'Saviour', description: 'Jesus is the Saviour of the world, sent by the Father to ransom sinners, conquer death and give eternal life to all that believe in Him.' },
    [VerseTagKey.Sin]: { key: VerseTagKey.Sin, name: 'Sin', description: 'Jesus has authority to forgive sin.' },
    [VerseTagKey.SoM]: { key: VerseTagKey.SoM, name: 'Son of Man', description: 'Jesus often calls Himself Son of Man. This title clearly references Daniel 7:13-14.' },
    [VerseTagKey.Son]: { key: VerseTagKey.Son, name: 'Son of God', description: 'The Father-Son relationship between God the Father and Jesus the Son' },
    [VerseTagKey.Trinity]: { key: VerseTagKey.Trinity, name: 'Trinity', description: 'The three persons of the trinity have different roles, but are intimitely interrelated.' },
    [VerseTagKey.Unique]: { key: VerseTagKey.Unique, name: 'Unique', description: 'Jesus is utterly unique from every other human in many ways.' },
    [VerseTagKey.Worship]: { key: VerseTagKey.Worship, name: 'Worship', description: 'Jesus is worshipped' },
    [VerseTagKey.Worthy]: { key: VerseTagKey.Worthy, name: 'Worthy', description: 'Jesus is worthy of much and worthier than many.' },
    [VerseTagKey.YHWH]: { key: VerseTagKey.YHWH, name: 'YHWH', description: 'The tettragramaton is God\'s unique name in the Old Testament. Verses and concepts that apply to Him are applied to Jesus in the New Testament.' },
    [VerseTagKey.Sacrifice]: { key: VerseTagKey.Sacrifice, name: 'Sacrifice', description: 'Jesus was a sacrifice for sins; the perfect, prophesied Lamb of God.' },
    [VerseTagKey.Word]: { key: VerseTagKey.Word, name: 'Word', description: '' },
    [VerseTagKey.Immanuel]: { key: VerseTagKey.Immanuel, name: 'Immanuel', description: '' },
    [VerseTagKey.Light]: { key: VerseTagKey.Light, name: 'Light', description: '' },
    [VerseTagKey.Shepherd]: { key: VerseTagKey.Shepherd, name: 'Shepherd', description: '' },
};
