import { BibleBookMap, BibleBookKey } from '../../models/bible';

export const bibleBooks: BibleBookMap = {
    [BibleBookKey.Gen]: { key: BibleBookKey.Gen, full: '1. Mose', abbr: '1. Mos.' },
    [BibleBookKey.Ex]: { key: BibleBookKey.Ex, full: '2. Mose', abbr: '2. Mos.' },
    [BibleBookKey.Lev]: { key: BibleBookKey.Lev, full: '3. Mose', abbr: '3. Mos.' },
    [BibleBookKey.Num]: { key: BibleBookKey.Num, full: '4. Mose', abbr: '4. Mos.' },
    [BibleBookKey.Deut]: { key: BibleBookKey.Deut, full: '5. Mose', abbr: '5. Mos.' },
    [BibleBookKey.Josh]: { key: BibleBookKey.Josh, full: 'Josua', abbr: 'Jos.' },
    [BibleBookKey.Judg]: { key: BibleBookKey.Judg, full: 'Richter', abbr: 'Ri.' },
    [BibleBookKey.Ruth]: { key: BibleBookKey.Ruth, full: 'Rut', abbr: 'Rut' },
    [BibleBookKey.Sam1]: { key: BibleBookKey.Sam1, full: '1. Samuel', abbr: '1. Sam.' },
    [BibleBookKey.Sam2]: { key: BibleBookKey.Sam2, full: '2. Samuel', abbr: '2. Sam.' },
    [BibleBookKey.Kings1]: { key: BibleBookKey.Kings1, full: '1. Könige', abbr: '1. Kön.' },
    [BibleBookKey.Kings2]: { key: BibleBookKey.Kings2, full: '2. Könige', abbr: '2. Kön.' },
    [BibleBookKey.Chron1]: { key: BibleBookKey.Chron1, full: '1. Chronik', abbr: '1. Chr.' },
    [BibleBookKey.Chron2]: { key: BibleBookKey.Chron2, full: '2. Chronik', abbr: '2. Chr.' },
    [BibleBookKey.Ezra]: { key: BibleBookKey.Ezra, full: 'Esra', abbr: 'Esra' },
    [BibleBookKey.Neh]: { key: BibleBookKey.Neh, full: 'Nehemia', abbr: 'Neh.' },
    [BibleBookKey.Est]: { key: BibleBookKey.Est, full: 'Ester', abbr: 'Est.' },
    [BibleBookKey.Job]: { key: BibleBookKey.Job, full: 'Hiob', abbr: 'Hiob' },
    [BibleBookKey.Ps]: { key: BibleBookKey.Ps, full: 'Psalmen', abbr: 'Ps.' },
    [BibleBookKey.Prov]: { key: BibleBookKey.Prov, full: 'Sprüche', abbr: 'Spr.' },
    [BibleBookKey.Eccles]: { key: BibleBookKey.Eccles, full: 'Prediger', abbr: 'Pred.' },
    [BibleBookKey.Song]: { key: BibleBookKey.Song, full: 'Hoheslied', abbr: 'Hld.' },
    [BibleBookKey.Isa]: { key: BibleBookKey.Isa, full: 'Jesaja', abbr: 'Jes.' },
    [BibleBookKey.Jer]: { key: BibleBookKey.Jer, full: 'Jeremia', abbr: 'Jer.' },
    [BibleBookKey.Lam]: { key: BibleBookKey.Lam, full: 'Klagelieder', abbr: 'Klgl.' },
    [BibleBookKey.Ezek]: { key: BibleBookKey.Ezek, full: 'Hesekiel', abbr: 'Hes.' },
    [BibleBookKey.Dan]: { key: BibleBookKey.Dan, full: 'Daniel', abbr: 'Dan.' },
    [BibleBookKey.Hos]: { key: BibleBookKey.Hos, full: 'Hosea', abbr: 'Hos.' },
    [BibleBookKey.Joel]: { key: BibleBookKey.Joel, full: 'Joel', abbr: 'Joel' },
    [BibleBookKey.Amos]: { key: BibleBookKey.Amos, full: 'Amos', abbr: 'Amos' },
    [BibleBookKey.Obad]: { key: BibleBookKey.Obad, full: 'Obadja', abbr: 'Obd.' },
    [BibleBookKey.Jonah]: { key: BibleBookKey.Jonah, full: 'Jona', abbr: 'Jona' },
    [BibleBookKey.Mic]: { key: BibleBookKey.Mic, full: 'Micha', abbr: 'Micha' },
    [BibleBookKey.Nah]: { key: BibleBookKey.Nah, full: 'Nahum', abbr: 'Nah.' },
    [BibleBookKey.Hab]: { key: BibleBookKey.Hab, full: 'Habakuk', abbr: 'Hab.' },
    [BibleBookKey.Zeph]: { key: BibleBookKey.Zeph, full: 'Zefanja', abbr: 'Zef.' },
    [BibleBookKey.Hag]: { key: BibleBookKey.Hag, full: 'Haggai', abbr: 'Hag.' },
    [BibleBookKey.Zech]: { key: BibleBookKey.Zech, full: 'Sacharja', abbr: 'Sach.' },
    [BibleBookKey.Mal]: { key: BibleBookKey.Mal, full: 'Maleachi', abbr: 'Mal.' },
    [BibleBookKey.Matt]: { key: BibleBookKey.Matt, full: 'Matthäus', abbr: 'Matt.' },
    [BibleBookKey.Mark]: { key: BibleBookKey.Mark, full: 'Markus', abbr: 'Mk.' },
    [BibleBookKey.Luke]: { key: BibleBookKey.Luke, full: 'Lukas', abbr: 'Lk.' },
    [BibleBookKey.John]: { key: BibleBookKey.John, full: 'Johannes', abbr: 'Joh.' },
    [BibleBookKey.Acts]: { key: BibleBookKey.Acts, full: 'Apostelgeschichte', abbr: 'Apg.' },
    [BibleBookKey.Rom]: { key: BibleBookKey.Rom, full: 'Römer', abbr: 'Röm.' },
    [BibleBookKey.Cor1]: { key: BibleBookKey.Cor1, full: '1. Korinther', abbr: '1. Kor.' },
    [BibleBookKey.Cor2]: { key: BibleBookKey.Cor2, full: '2. Korinther', abbr: '2. Kor.' },
    [BibleBookKey.Gal]: { key: BibleBookKey.Gal, full: 'Galater', abbr: 'Gal.' },
    [BibleBookKey.Eph]: { key: BibleBookKey.Eph, full: 'Epheser', abbr: 'Eph.' },
    [BibleBookKey.Phil]: { key: BibleBookKey.Phil, full: 'Philipper', abbr: 'Phil.' },
    [BibleBookKey.Col]: { key: BibleBookKey.Col, full: 'Kolosser', abbr: 'Kol.' },
    [BibleBookKey.Thess1]: { key: BibleBookKey.Thess1, full: '1. Thessalonicher', abbr: '1. Thess.' },
    [BibleBookKey.Thess2]: { key: BibleBookKey.Thess2, full: '2. Thessalonicher', abbr: '2. Thess.' },
    [BibleBookKey.Tim1]: { key: BibleBookKey.Tim1, full: '1. Timotheus', abbr: '1. Tim.' },
    [BibleBookKey.Tim2]: { key: BibleBookKey.Tim2, full: '2. Timotheus', abbr: '2. Tim.' },
    [BibleBookKey.Titus]: { key: BibleBookKey.Titus, full: 'Titus', abbr: 'Tit.' },
    [BibleBookKey.Philem]: { key: BibleBookKey.Philem, full: 'Philemon', abbr: 'Phlm.' },
    [BibleBookKey.Heb]: { key: BibleBookKey.Heb, full: 'Hebräer', abbr: 'Hebr.' },
    [BibleBookKey.James]: { key: BibleBookKey.James, full: 'Jakobus', abbr: 'Jak.' },
    [BibleBookKey.Pet1]: { key: BibleBookKey.Pet1, full: '1. Petrus', abbr: '1. Petr.' },
    [BibleBookKey.Pet2]: { key: BibleBookKey.Pet2, full: '2. Petrus', abbr: '2. Petr.' },
    [BibleBookKey.John1]: { key: BibleBookKey.John1, full: '1. Johannes', abbr: '1. Joh.' },
    [BibleBookKey.John2]: { key: BibleBookKey.John2, full: '2. Johannes', abbr: '2. Joh.' },
    [BibleBookKey.John3]: { key: BibleBookKey.John3, full: '3. Johannes', abbr: '3. Joh.' },
    [BibleBookKey.Jude]: { key: BibleBookKey.Jude, full: 'Judas', abbr: 'Jud.' },
    [BibleBookKey.Rev]: { key: BibleBookKey.Rev, full: 'Offenbarung', abbr: 'Offb.' },
};
