import { VerseTagMap, VerseTagKey } from '../../models/tags';

// tslint:disable:max-line-length
export const tags: VerseTagMap = {
    [VerseTagKey.Authority]: { key: VerseTagKey.Authority, name: 'Autorität', description: 'Jesus demonstrated great authority over disease, nature, demons, etc. Most noteworthy is, perhaps, how Jesus performs the miracles without explicitly calling on the help of God.' },
    [VerseTagKey.Blasphemy]: { key: VerseTagKey.Blasphemy, name: 'Gotteslästerung', description: 'Jesus accused of blasphemy on multiple occasions. Usually, because His hearers feel that He is acting as God.' },
    [VerseTagKey.Bridegroom]: { key: VerseTagKey.Bridegroom, name: 'Bräutigam', description: 'Jesus claims to be the bridegroom of the church, His bride.' },
    [VerseTagKey.Christ]: { key: VerseTagKey.Christ, name: 'Christus', description: 'Jeus is the Christ (or promised Messiah), often identified as the son of David.' },
    [VerseTagKey.Clean]: { key: VerseTagKey.Clean, name: 'Rein', description: 'Jesus heals the unclean. Religious cleanliness is tightly tied to an understanding of sinfulness.' },
    [VerseTagKey.Clouds]: { key: VerseTagKey.Clouds, name: 'Wolken', description: 'Clouds are used in the Bible to represent the presence and glory of God (eg. Ex. 16:10, Ex. 40:34-35, Num. 11:25).' },
    [VerseTagKey.Creator]: { key: VerseTagKey.Creator, name: 'Schöpfer', description: 'All things were created through Jesus.' },
    [VerseTagKey.Demons]: { key: VerseTagKey.Demons, name: 'Dämonen', description: 'Demons had a remarkably high view of Jesus.' },
    [VerseTagKey.Eternal]: { key: VerseTagKey.Eternal, name: 'Ewig', description: 'Jesus is the same yesterday and today and forever. In the beginning He already was and He always will be.' },
    [VerseTagKey.Faith]: { key: VerseTagKey.Faith, name: 'Glaube', description: 'Jesus is the object of people\'s faith.' },
    [VerseTagKey.FP]: { key: VerseTagKey.FP, name: 'Erfüllte Prophezeiung', description: 'Jesus is the fulfillment of many prophecies in the Old Testament.' },
    [VerseTagKey.Glory]: { key: VerseTagKey.Glory, name: 'Herrlichkeit', description: 'Great glory is ascribed to Jesus; even the glory of the Father.' },
    [VerseTagKey.God]: { key: VerseTagKey.God, name: 'Gott', description: 'Jesus is sometimes explicitly and sometimes implicitly made out to be God.' },
    [VerseTagKey.Greater]: { key: VerseTagKey.Greater, name: 'Größer', description: 'Jesus is greater than a great many great people and things.' },
    [VerseTagKey.Heaven]: { key: VerseTagKey.Heaven, name: 'Himmel', description: 'Jesus came down from Heaven, indicating that He existed before He was born.' },
    [VerseTagKey.Himself]: { key: VerseTagKey.Himself, name: 'Selbst', description: 'Jesus had many extraordinary things to say about Himself.' },
    [VerseTagKey.His]: { key: VerseTagKey.His, name: 'Seins', description: 'People, beings, things and positions are described as belonging to Jesus.' },
    [VerseTagKey.Holy]: { key: VerseTagKey.Holy, name: 'Heilig', description: 'Jesus is holy and pure.' },
    [VerseTagKey.Honour]: { key: VerseTagKey.Honour, name: 'Ehre', description: 'Jesus is often honoured in extroardinary ways.' },
    [VerseTagKey.Humility]: { key: VerseTagKey.Humility, name: 'Demut', description: 'Jesus\' highest priority was not showing off exactly who He was to everyone.' },
    [VerseTagKey.I_AM]: { key: VerseTagKey.I_AM, name: 'ICH BIN', description: 'The God of the Old Testament reveals Himself to Moses as the "I AM" (Ex. 3:14). Jesus seems to use this same title.' },
    [VerseTagKey.Judge]: { key: VerseTagKey.Judge, name: 'Richter', description: 'Jesus will judge the world one day.' },
    [VerseTagKey.King]: { key: VerseTagKey.King, name: 'König', description: 'Jesus is the king of an eternal kingdom.' },
    [VerseTagKey.Life]: { key: VerseTagKey.Life, name: 'Leben', description: 'Jesus is not only the source of life, but life itself.' },
    [VerseTagKey.Lord]: { key: VerseTagKey.Lord, name: 'Herr', description: 'Jesus is a lord. In fact many passages refer to both God and Jesus as lord using the same Greek word (Kyrios) without attempting to make any distinction.' },
    [VerseTagKey.Lowly]: { key: VerseTagKey.Lowly, name: 'Niedrig', description: 'Jesus sometimes seemingly distanced Himself from equality with God, His Father.' },
    [VerseTagKey.Name]: { key: VerseTagKey.Name, name: 'Name', description: 'Jesus\' "name" is authoritative, emphasized and honoured.' },
    [VerseTagKey.Omnipresent]: { key: VerseTagKey.Omnipresent, name: 'Allgegenwärtig', description: 'Jesus makes claims that require Him to be in multiple places at the same time. ' },
    [VerseTagKey.Omniscient]: { key: VerseTagKey.Omniscient, name: 'Allwissend', description: 'Jesus\' knowledge is hard to overexaggerate.' },
    [VerseTagKey.One]: { key: VerseTagKey.One, name: 'Eins', description: 'Jesus, the Son, is intimately united with His Father.' },
    [VerseTagKey.Power]: { key: VerseTagKey.Power, name: 'Macht', description: 'Jesus demonstrated power over disease, demons and nature.' },
    [VerseTagKey.Right_Hand]: { key: VerseTagKey.Right_Hand, name: 'Rechter Hand', description: 'Jesus sits at the right hand of God.' },
    [VerseTagKey.Saviour]: { key: VerseTagKey.Saviour, name: 'Retter', description: 'Jesus is the Saviour of the world, sent by the Father to ransom sinners, conquer death and give eternal life to all that believe in Him.' },
    [VerseTagKey.Sin]: { key: VerseTagKey.Sin, name: 'Sünde', description: 'Jesus has authority to forgive sin.' },
    [VerseTagKey.SoM]: { key: VerseTagKey.SoM, name: 'Menschensohn', description: 'Jesus often calls Himself the "Son of Man", clearly referencing Daniel 7:13-14.' },
    [VerseTagKey.Son]: { key: VerseTagKey.Son, name: 'Gottessohn', description: 'Jesus is the only true Son of the Father.' },
    [VerseTagKey.Trinity]: { key: VerseTagKey.Trinity, name: 'Dreieinigkeit', description: 'Jesus is the second person of the trinity. He plays a unique role, but all three are intimitely interrelated.' },
    [VerseTagKey.Unique]: { key: VerseTagKey.Unique, name: 'Einmalig', description: 'Jesus is utterly unique from every other human in many ways.' },
    [VerseTagKey.Worship]: { key: VerseTagKey.Worship, name: 'Anbetung', description: 'Jesus receives and accepts worship.' },
    [VerseTagKey.Worthy]: { key: VerseTagKey.Worthy, name: 'Würdig', description: 'Jesus is worthy of much and worthier than many.' },
    [VerseTagKey.YHWH]: { key: VerseTagKey.YHWH, name: 'YHWH', description: 'The tetragrammaton is God\'s unique name in the Old Testament. Verses and concepts that apply to Him are applied to Jesus in the New Testament.' },
    [VerseTagKey.Sacrifice]: { key: VerseTagKey.Sacrifice, name: 'Opfer', description: 'Jesus was a sacrifice for sins; the perfect, prophesied Lamb of God.' },
    [VerseTagKey.Word]: { key: VerseTagKey.Word, name: 'Wort', description: '' },
    [VerseTagKey.Immanuel]: { key: VerseTagKey.Immanuel, name: 'Immanuel', description: '' },
    [VerseTagKey.Light]: { key: VerseTagKey.Light, name: 'Licht', description: '' },
    [VerseTagKey.Shepherd]: { key: VerseTagKey.Shepherd, name: 'Hirte', description: 'Jesus is a shepherd to His followers.' },
};
