import { VerseTagMap, VerseTagKey } from '../../models/tags';

// tslint:disable:max-line-length
export const tags: VerseTagMap = {
    [VerseTagKey.Authority]: { key: VerseTagKey.Authority, name: 'Autorität', description: 'Jesus zeigte Autorität über Krankheit, Natur, Dämonen etc. Merkwürdig ist, dass er Wunder bewirkt ohne sich explicit auf Gottes Hilfe zu berufen.' },
    [VerseTagKey.Blasphemy]: { key: VerseTagKey.Blasphemy, name: 'Gotteslästerung', description: 'Jesus wird mehrmals Gotteslästerung vorgeworfen. Meistens dann, wenn seine Zuhörer meinen, er stelle sich auf Gottes Position.' },
    [VerseTagKey.Bridegroom]: { key: VerseTagKey.Bridegroom, name: 'Bräutigam', description: 'Jesus behauptet er sei der Bräutigam der Kirche, seiner Braut.' },
    [VerseTagKey.Christ]: { key: VerseTagKey.Christ, name: 'Christus', description: 'Jesus ist der Christus (oder verheißener Messias) oft als Sohn Davids bezeichnet.' },
    [VerseTagKey.Clean]: { key: VerseTagKey.Clean, name: 'Rein', description: 'Jesus heilt die Unreinen. Religiöse Reinheit wird in engem Zusammenhang mit Sünde vertsanden.' },
    [VerseTagKey.Clouds]: { key: VerseTagKey.Clouds, name: 'Wolken', description: 'Wolken in der Bibel stellen Gottes Gegenwart oder Herrlichkeit dar (z.B. 2. Mose 16,10; 40,34-35; 4. Mose 11,25).' },
    [VerseTagKey.Creator]: { key: VerseTagKey.Creator, name: 'Schöpfer', description: 'Alles wurde durch Jesus erschaffen.' },
    [VerseTagKey.Demons]: { key: VerseTagKey.Demons, name: 'Dämonen', description: 'Dämonen hielten viel von Jesus.' },
    [VerseTagKey.Eternal]: { key: VerseTagKey.Eternal, name: 'Ewig', description: 'Jesus ist derselbe gestern, heute und in Ewigkeit. Er war am Anfang und wird für immer sein.' },
    [VerseTagKey.Faith]: { key: VerseTagKey.Faith, name: 'Glaube', description: 'Jesus ist das Objekt des Glaubens vieler Menschen.' },
    [VerseTagKey.FP]: { key: VerseTagKey.FP, name: 'Erfüllte Prophezeiung', description: 'Jesus ist die Erfüllung viele alttestamentlicher Prophezeiungen.' },
    [VerseTagKey.Glory]: { key: VerseTagKey.Glory, name: 'Herrlichkeit', description: 'Große Herrlichkeit wird Jesus zugeschrieben; sogar die Herrlichkeit seines Vaters.' },
    [VerseTagKey.God]: { key: VerseTagKey.God, name: 'Gott', description: 'Jesus wird (teils explizit und teils implizit) als Gott dargestellt.' },
    [VerseTagKey.Greater]: { key: VerseTagKey.Greater, name: 'Größer', description: 'Jesus ist größer als eine großartige Menge von großen Menschen und Sachen.' },
    [VerseTagKey.Heaven]: { key: VerseTagKey.Heaven, name: 'Himmel', description: 'Jesus kam vom Himmel und existierte daher auch bevor er geboren wurde.' },
    [VerseTagKey.Himself]: { key: VerseTagKey.Himself, name: 'Jesus Selbst', description: 'Jesus hatte viel Erstaunliches über sich selbst zu sagen.' },
    [VerseTagKey.His]: { key: VerseTagKey.His, name: 'Seines', description: 'Menschen, Wesen, Sachen und Stellen werden als Jesu Eigentum beschrieben.' },
    [VerseTagKey.Holy]: { key: VerseTagKey.Holy, name: 'Heilig', description: 'Jesus ist heilig und rein.' },
    [VerseTagKey.Honour]: { key: VerseTagKey.Honour, name: 'Ehre', description: 'Jesus wird auf erstaunlicher Weise geehrt.' },
    [VerseTagKey.Humility]: { key: VerseTagKey.Humility, name: 'Demut', description: 'Jesus verzichtete darauf, sich jedem vollkommen zu offenbaren.' },
    [VerseTagKey.I_AM]: { key: VerseTagKey.I_AM, name: 'ICH BIN', description: 'Der Gott des Altentestamentes offenbart sich Mose als der "ICH BIN" (2. Mose 3,14). Jesus scheint diesen Titel auch zu beanspruchen.' },
    [VerseTagKey.Judge]: { key: VerseTagKey.Judge, name: 'Richter', description: 'Jesus wird eines Tages die Welt richten.' },
    [VerseTagKey.King]: { key: VerseTagKey.King, name: 'König', description: 'Jesus ist König eines ewigen Reiches.' },
    [VerseTagKey.Life]: { key: VerseTagKey.Life, name: 'Leben', description: 'Jesus ist nicht nur die Quelle des Lebens, sondern Leben selbst.' },
    [VerseTagKey.Lord]: { key: VerseTagKey.Lord, name: 'Herr', description: 'Jesus ist ein Herr. Noch dazu bezeichnen manche Texte sowohl ihn als auch Gott mit dem gleichen griechischen Wort (Kyrios) ohne eine Unterscheidung zu machen.' },
    [VerseTagKey.Lowly]: { key: VerseTagKey.Lowly, name: 'Niedrig', description: 'Jesus scheint sich manchmal von einer Gleichstellung mit Gott, seinem Vater, zu distanzieren.' },
    [VerseTagKey.Name]: { key: VerseTagKey.Name, name: 'Name', description: 'Jesu "Name" trägt Autorität und wird geehrt und hervorgehoben.' },
    [VerseTagKey.Omnipresent]: { key: VerseTagKey.Omnipresent, name: 'Allgegenwärtig', description: 'Jesu Behauptungen fordern von Ihm gleichzeitich an mehreren Orten zu sein.' },
    [VerseTagKey.Omniscient]: { key: VerseTagKey.Omniscient, name: 'Allwissend', description: 'Jesu Wissen kann mann nicht überbewerten.' },
    [VerseTagKey.One]: { key: VerseTagKey.One, name: 'Eins', description: 'Jesus, der Sohn, ist innig vereint mit seinem Vater.' },
    [VerseTagKey.Power]: { key: VerseTagKey.Power, name: 'Macht', description: 'Jesus demonstrierte Macht über Krankheit, Dämonen und die Natur.' },
    [VerseTagKey.Right_Hand]: { key: VerseTagKey.Right_Hand, name: 'Rechte Hand', description: 'Jesus sitzt zur Rechten Gotten.' },
    [VerseTagKey.Saviour]: { key: VerseTagKey.Saviour, name: 'Retter', description: 'Jesus ist der Retter der Welt, gesandt vom Vater um Sünder freizukaufen, den Tod zu besiegen und jedem, der an Ihn glaubt, ewiges Leben zu schenken.' },
    [VerseTagKey.Sin]: { key: VerseTagKey.Sin, name: 'Sünde', description: 'Jesus hat Autorität Sünden zu vergeben.' },
    [VerseTagKey.SoM]: { key: VerseTagKey.SoM, name: 'Menschensohn', description: 'Jesus nennt sich oft "Menschensohn", was sich deutlich auf Daniel 7,13-14 bezieht.' },
    [VerseTagKey.Son]: { key: VerseTagKey.Son, name: 'Gottes Sohn', description: 'Jesus ist der einzige wahre Sohn des Vaters.' },
    [VerseTagKey.Trinity]: { key: VerseTagKey.Trinity, name: 'Dreieinigkeit', description: 'Jesus ist die zweite Person der Dreieinigkeit. Trotz seiner einmaligen Rolle stehen alle drei in inniger gegenseitiger Beziehung.' },
    [VerseTagKey.Unique]: { key: VerseTagKey.Unique, name: 'Einmalig', description: 'Jesus ist äußerst einmalig im Vergleich zu allen anderen Menschen.' },
    [VerseTagKey.Worship]: { key: VerseTagKey.Worship, name: 'Anbetung', description: 'Jesus bekommt und akzeptiert Anbetung.' },
    [VerseTagKey.Worthy]: { key: VerseTagKey.Worthy, name: 'Würdig', description: 'Jesus ist vielem würdig und würdiger als viele.' },
    [VerseTagKey.YHWH]: { key: VerseTagKey.YHWH, name: 'YHWH', description: 'Das Tetragramm ist Gottes einmaliger Name im Alten Testament. Verse und Konzepte die von Ihm handeln, werden im Neuen Testament für Jesus angewendet.' },
    [VerseTagKey.Sacrifice]: { key: VerseTagKey.Sacrifice, name: 'Opfer', description: 'Jesus war ein Sündopfer; das makellose, verheißene Lamm Gottes.' },
    [VerseTagKey.Word]: { key: VerseTagKey.Word, name: 'Wort', description: '' },
    [VerseTagKey.Immanuel]: { key: VerseTagKey.Immanuel, name: 'Immanuel', description: '' },
    [VerseTagKey.Light]: { key: VerseTagKey.Light, name: 'Licht', description: '' },
    [VerseTagKey.Shepherd]: { key: VerseTagKey.Shepherd, name: 'Hirte', description: 'Jesus ist ein Hirte für seine Nachfolger.' },
};
